ps4-policy(8)

# NAME

ps4 policy - show repository policy for packages

# SYNOPSIS

*ps4 policy* [<_options_>...] _packages_...

# DESCRIPTION

*ps4 policy* shows ps4's repository policy for the specified packages. It
prints matching packages and their versions available from configured
repositories (see *ps4-repositories*(5)), sorted by ascending version.

# OPTIONS

*ps4 policy* does not support any specific options. See *ps4*(8) for global
options.
